version: "3.9"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
    ports:
      - "2050:2050"
